// Generated by gencpp from file messages/ImageCaptureRequest.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_IMAGECAPTUREREQUEST_H
#define MESSAGES_MESSAGE_IMAGECAPTUREREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages
{
template <class ContainerAllocator>
struct ImageCaptureRequest_
{
  typedef ImageCaptureRequest_<ContainerAllocator> Type;

  ImageCaptureRequest_()
    : x(false)  {
    }
  ImageCaptureRequest_(const ContainerAllocator& _alloc)
    : x(false)  {
  (void)_alloc;
    }



   typedef uint8_t _x_type;
  _x_type x;





  typedef boost::shared_ptr< ::messages::ImageCaptureRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::ImageCaptureRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ImageCaptureRequest_

typedef ::messages::ImageCaptureRequest_<std::allocator<void> > ImageCaptureRequest;

typedef boost::shared_ptr< ::messages::ImageCaptureRequest > ImageCaptureRequestPtr;
typedef boost::shared_ptr< ::messages::ImageCaptureRequest const> ImageCaptureRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::ImageCaptureRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::ImageCaptureRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::messages::ImageCaptureRequest_<ContainerAllocator1> & lhs, const ::messages::ImageCaptureRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::messages::ImageCaptureRequest_<ContainerAllocator1> & lhs, const ::messages::ImageCaptureRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::messages::ImageCaptureRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::ImageCaptureRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::ImageCaptureRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::ImageCaptureRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::ImageCaptureRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::ImageCaptureRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::ImageCaptureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e7c7f7c11db7cc314e9efb95e17c2ed";
  }

  static const char* value(const ::messages::ImageCaptureRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e7c7f7c11db7cc3ULL;
  static const uint64_t static_value2 = 0x14e9efb95e17c2edULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::ImageCaptureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/ImageCaptureRequest";
  }

  static const char* value(const ::messages::ImageCaptureRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::ImageCaptureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool x\n"
;
  }

  static const char* value(const ::messages::ImageCaptureRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::ImageCaptureRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageCaptureRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::ImageCaptureRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::ImageCaptureRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_IMAGECAPTUREREQUEST_H
