// Generated by gencpp from file franka_control/SetForceTorqueCollisionBehavior.msg
// DO NOT EDIT!


#ifndef FRANKA_CONTROL_MESSAGE_SETFORCETORQUECOLLISIONBEHAVIOR_H
#define FRANKA_CONTROL_MESSAGE_SETFORCETORQUECOLLISIONBEHAVIOR_H

#include <ros/service_traits.h>


#include <franka_control/SetForceTorqueCollisionBehaviorRequest.h>
#include <franka_control/SetForceTorqueCollisionBehaviorResponse.h>


namespace franka_control
{

struct SetForceTorqueCollisionBehavior
{

typedef SetForceTorqueCollisionBehaviorRequest Request;
typedef SetForceTorqueCollisionBehaviorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetForceTorqueCollisionBehavior
} // namespace franka_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_control::SetForceTorqueCollisionBehavior > {
  static const char* value()
  {
    return "b1e592d1b6960bc05e6e3cba1eb02349";
  }

  static const char* value(const ::franka_control::SetForceTorqueCollisionBehavior&) { return value(); }
};

template<>
struct DataType< ::franka_control::SetForceTorqueCollisionBehavior > {
  static const char* value()
  {
    return "franka_control/SetForceTorqueCollisionBehavior";
  }

  static const char* value(const ::franka_control::SetForceTorqueCollisionBehavior&) { return value(); }
};


// service_traits::MD5Sum< ::franka_control::SetForceTorqueCollisionBehaviorRequest> should match
// service_traits::MD5Sum< ::franka_control::SetForceTorqueCollisionBehavior >
template<>
struct MD5Sum< ::franka_control::SetForceTorqueCollisionBehaviorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_control::SetForceTorqueCollisionBehavior >::value();
  }
  static const char* value(const ::franka_control::SetForceTorqueCollisionBehaviorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_control::SetForceTorqueCollisionBehaviorRequest> should match
// service_traits::DataType< ::franka_control::SetForceTorqueCollisionBehavior >
template<>
struct DataType< ::franka_control::SetForceTorqueCollisionBehaviorRequest>
{
  static const char* value()
  {
    return DataType< ::franka_control::SetForceTorqueCollisionBehavior >::value();
  }
  static const char* value(const ::franka_control::SetForceTorqueCollisionBehaviorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_control::SetForceTorqueCollisionBehaviorResponse> should match
// service_traits::MD5Sum< ::franka_control::SetForceTorqueCollisionBehavior >
template<>
struct MD5Sum< ::franka_control::SetForceTorqueCollisionBehaviorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_control::SetForceTorqueCollisionBehavior >::value();
  }
  static const char* value(const ::franka_control::SetForceTorqueCollisionBehaviorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_control::SetForceTorqueCollisionBehaviorResponse> should match
// service_traits::DataType< ::franka_control::SetForceTorqueCollisionBehavior >
template<>
struct DataType< ::franka_control::SetForceTorqueCollisionBehaviorResponse>
{
  static const char* value()
  {
    return DataType< ::franka_control::SetForceTorqueCollisionBehavior >::value();
  }
  static const char* value(const ::franka_control::SetForceTorqueCollisionBehaviorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_CONTROL_MESSAGE_SETFORCETORQUECOLLISIONBEHAVIOR_H
