// Generated by gencpp from file franka_control/SetJointImpedanceRequest.msg
// DO NOT EDIT!


#ifndef FRANKA_CONTROL_MESSAGE_SETJOINTIMPEDANCEREQUEST_H
#define FRANKA_CONTROL_MESSAGE_SETJOINTIMPEDANCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace franka_control
{
template <class ContainerAllocator>
struct SetJointImpedanceRequest_
{
  typedef SetJointImpedanceRequest_<ContainerAllocator> Type;

  SetJointImpedanceRequest_()
    : joint_stiffness()  {
      joint_stiffness.assign(0.0);
  }
  SetJointImpedanceRequest_(const ContainerAllocator& _alloc)
    : joint_stiffness()  {
  (void)_alloc;
      joint_stiffness.assign(0.0);
  }



   typedef boost::array<double, 7>  _joint_stiffness_type;
  _joint_stiffness_type joint_stiffness;





  typedef boost::shared_ptr< ::franka_control::SetJointImpedanceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_control::SetJointImpedanceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointImpedanceRequest_

typedef ::franka_control::SetJointImpedanceRequest_<std::allocator<void> > SetJointImpedanceRequest;

typedef boost::shared_ptr< ::franka_control::SetJointImpedanceRequest > SetJointImpedanceRequestPtr;
typedef boost::shared_ptr< ::franka_control::SetJointImpedanceRequest const> SetJointImpedanceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_control::SetJointImpedanceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_control::SetJointImpedanceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace franka_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'franka_control': ['/home/rnm/catkin_ws/devel/share/franka_control/msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::franka_control::SetJointImpedanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_control::SetJointImpedanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_control::SetJointImpedanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_control::SetJointImpedanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_control::SetJointImpedanceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_control::SetJointImpedanceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_control::SetJointImpedanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45e5482efb638f20554d876158c68e96";
  }

  static const char* value(const ::franka_control::SetJointImpedanceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45e5482efb638f20ULL;
  static const uint64_t static_value2 = 0x554d876158c68e96ULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_control::SetJointImpedanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_control/SetJointImpedanceRequest";
  }

  static const char* value(const ::franka_control::SetJointImpedanceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_control::SetJointImpedanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[7] joint_stiffness\n"
;
  }

  static const char* value(const ::franka_control::SetJointImpedanceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_control::SetJointImpedanceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_stiffness);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointImpedanceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_control::SetJointImpedanceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::franka_control::SetJointImpedanceRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_stiffness[]" << std::endl;
    for (size_t i = 0; i < v.joint_stiffness.size(); ++i)
    {
      s << indent << "  joint_stiffness[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_stiffness[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_CONTROL_MESSAGE_SETJOINTIMPEDANCEREQUEST_H
