// Generated by gencpp from file franka_control/SetJointImpedance.msg
// DO NOT EDIT!


#ifndef FRANKA_CONTROL_MESSAGE_SETJOINTIMPEDANCE_H
#define FRANKA_CONTROL_MESSAGE_SETJOINTIMPEDANCE_H

#include <ros/service_traits.h>


#include <franka_control/SetJointImpedanceRequest.h>
#include <franka_control/SetJointImpedanceResponse.h>


namespace franka_control
{

struct SetJointImpedance
{

typedef SetJointImpedanceRequest Request;
typedef SetJointImpedanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointImpedance
} // namespace franka_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_control::SetJointImpedance > {
  static const char* value()
  {
    return "f11c4defa2a13040512214f9d77dc982";
  }

  static const char* value(const ::franka_control::SetJointImpedance&) { return value(); }
};

template<>
struct DataType< ::franka_control::SetJointImpedance > {
  static const char* value()
  {
    return "franka_control/SetJointImpedance";
  }

  static const char* value(const ::franka_control::SetJointImpedance&) { return value(); }
};


// service_traits::MD5Sum< ::franka_control::SetJointImpedanceRequest> should match
// service_traits::MD5Sum< ::franka_control::SetJointImpedance >
template<>
struct MD5Sum< ::franka_control::SetJointImpedanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_control::SetJointImpedance >::value();
  }
  static const char* value(const ::franka_control::SetJointImpedanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_control::SetJointImpedanceRequest> should match
// service_traits::DataType< ::franka_control::SetJointImpedance >
template<>
struct DataType< ::franka_control::SetJointImpedanceRequest>
{
  static const char* value()
  {
    return DataType< ::franka_control::SetJointImpedance >::value();
  }
  static const char* value(const ::franka_control::SetJointImpedanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_control::SetJointImpedanceResponse> should match
// service_traits::MD5Sum< ::franka_control::SetJointImpedance >
template<>
struct MD5Sum< ::franka_control::SetJointImpedanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_control::SetJointImpedance >::value();
  }
  static const char* value(const ::franka_control::SetJointImpedanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_control::SetJointImpedanceResponse> should match
// service_traits::DataType< ::franka_control::SetJointImpedance >
template<>
struct DataType< ::franka_control::SetJointImpedanceResponse>
{
  static const char* value()
  {
    return DataType< ::franka_control::SetJointImpedance >::value();
  }
  static const char* value(const ::franka_control::SetJointImpedanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_CONTROL_MESSAGE_SETJOINTIMPEDANCE_H
