// Generated by gencpp from file franka_control/SetKFrame.msg
// DO NOT EDIT!


#ifndef FRANKA_CONTROL_MESSAGE_SETKFRAME_H
#define FRANKA_CONTROL_MESSAGE_SETKFRAME_H

#include <ros/service_traits.h>


#include <franka_control/SetKFrameRequest.h>
#include <franka_control/SetKFrameResponse.h>


namespace franka_control
{

struct SetKFrame
{

typedef SetKFrameRequest Request;
typedef SetKFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetKFrame
} // namespace franka_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_control::SetKFrame > {
  static const char* value()
  {
    return "11b22d30e6a11a7b51828be575a77359";
  }

  static const char* value(const ::franka_control::SetKFrame&) { return value(); }
};

template<>
struct DataType< ::franka_control::SetKFrame > {
  static const char* value()
  {
    return "franka_control/SetKFrame";
  }

  static const char* value(const ::franka_control::SetKFrame&) { return value(); }
};


// service_traits::MD5Sum< ::franka_control::SetKFrameRequest> should match
// service_traits::MD5Sum< ::franka_control::SetKFrame >
template<>
struct MD5Sum< ::franka_control::SetKFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_control::SetKFrame >::value();
  }
  static const char* value(const ::franka_control::SetKFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_control::SetKFrameRequest> should match
// service_traits::DataType< ::franka_control::SetKFrame >
template<>
struct DataType< ::franka_control::SetKFrameRequest>
{
  static const char* value()
  {
    return DataType< ::franka_control::SetKFrame >::value();
  }
  static const char* value(const ::franka_control::SetKFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_control::SetKFrameResponse> should match
// service_traits::MD5Sum< ::franka_control::SetKFrame >
template<>
struct MD5Sum< ::franka_control::SetKFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_control::SetKFrame >::value();
  }
  static const char* value(const ::franka_control::SetKFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_control::SetKFrameResponse> should match
// service_traits::DataType< ::franka_control::SetKFrame >
template<>
struct DataType< ::franka_control::SetKFrameResponse>
{
  static const char* value()
  {
    return DataType< ::franka_control::SetKFrame >::value();
  }
  static const char* value(const ::franka_control::SetKFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_CONTROL_MESSAGE_SETKFRAME_H
