(cl:in-package franka_control-srv)
(cl:export '(LOWER_TORQUE_THRESHOLDS_NOMINAL-VAL
          LOWER_TORQUE_THRESHOLDS_NOMINAL
          UPPER_TORQUE_THRESHOLDS_NOMINAL-VAL
          UPPER_TORQUE_THRESHOLDS_NOMINAL
          LOWER_FORCE_THRESHOLDS_NOMINAL-VAL
          LOWER_FORCE_THRESHOLDS_NOMINAL
          UPPER_FORCE_THRESHOLDS_NOMINAL-VAL
          UPPER_FORCE_THRESHOLDS_NOMINAL
          SUCCESS-VAL
          SUCCESS
          ERROR-VAL
          ERROR
))