; Auto-generated. Do not edit!


(cl:in-package franka_control-msg)


;//! \htmlinclude ErrorRecoveryResult.msg.html

(cl:defclass <ErrorRecoveryResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ErrorRecoveryResult (<ErrorRecoveryResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ErrorRecoveryResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ErrorRecoveryResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name franka_control-msg:<ErrorRecoveryResult> is deprecated: use franka_control-msg:ErrorRecoveryResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ErrorRecoveryResult>) ostream)
  "Serializes a message object of type '<ErrorRecoveryResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ErrorRecoveryResult>) istream)
  "Deserializes a message object of type '<ErrorRecoveryResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ErrorRecoveryResult>)))
  "Returns string type for a message object of type '<ErrorRecoveryResult>"
  "franka_control/ErrorRecoveryResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ErrorRecoveryResult)))
  "Returns string type for a message object of type 'ErrorRecoveryResult"
  "franka_control/ErrorRecoveryResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ErrorRecoveryResult>)))
  "Returns md5sum for a message object of type '<ErrorRecoveryResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ErrorRecoveryResult)))
  "Returns md5sum for a message object of type 'ErrorRecoveryResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ErrorRecoveryResult>)))
  "Returns full string definition for message of type '<ErrorRecoveryResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ErrorRecoveryResult)))
  "Returns full string definition for message of type 'ErrorRecoveryResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ErrorRecoveryResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ErrorRecoveryResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ErrorRecoveryResult
))
