; Auto-generated. Do not edit!


(cl:in-package franka_control-msg)


;//! \htmlinclude ErrorRecoveryFeedback.msg.html

(cl:defclass <ErrorRecoveryFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ErrorRecoveryFeedback (<ErrorRecoveryFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ErrorRecoveryFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ErrorRecoveryFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name franka_control-msg:<ErrorRecoveryFeedback> is deprecated: use franka_control-msg:ErrorRecoveryFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ErrorRecoveryFeedback>) ostream)
  "Serializes a message object of type '<ErrorRecoveryFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ErrorRecoveryFeedback>) istream)
  "Deserializes a message object of type '<ErrorRecoveryFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ErrorRecoveryFeedback>)))
  "Returns string type for a message object of type '<ErrorRecoveryFeedback>"
  "franka_control/ErrorRecoveryFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ErrorRecoveryFeedback)))
  "Returns string type for a message object of type 'ErrorRecoveryFeedback"
  "franka_control/ErrorRecoveryFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ErrorRecoveryFeedback>)))
  "Returns md5sum for a message object of type '<ErrorRecoveryFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ErrorRecoveryFeedback)))
  "Returns md5sum for a message object of type 'ErrorRecoveryFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ErrorRecoveryFeedback>)))
  "Returns full string definition for message of type '<ErrorRecoveryFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ErrorRecoveryFeedback)))
  "Returns full string definition for message of type 'ErrorRecoveryFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ErrorRecoveryFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ErrorRecoveryFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ErrorRecoveryFeedback
))
