; Auto-generated. Do not edit!


(cl:in-package franka_control-msg)


;//! \htmlinclude ErrorRecoveryGoal.msg.html

(cl:defclass <ErrorRecoveryGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ErrorRecoveryGoal (<ErrorRecoveryGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ErrorRecoveryGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ErrorRecoveryGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name franka_control-msg:<ErrorRecoveryGoal> is deprecated: use franka_control-msg:ErrorRecoveryGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ErrorRecoveryGoal>) ostream)
  "Serializes a message object of type '<ErrorRecoveryGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ErrorRecoveryGoal>) istream)
  "Deserializes a message object of type '<ErrorRecoveryGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ErrorRecoveryGoal>)))
  "Returns string type for a message object of type '<ErrorRecoveryGoal>"
  "franka_control/ErrorRecoveryGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ErrorRecoveryGoal)))
  "Returns string type for a message object of type 'ErrorRecoveryGoal"
  "franka_control/ErrorRecoveryGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ErrorRecoveryGoal>)))
  "Returns md5sum for a message object of type '<ErrorRecoveryGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ErrorRecoveryGoal)))
  "Returns md5sum for a message object of type 'ErrorRecoveryGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ErrorRecoveryGoal>)))
  "Returns full string definition for message of type '<ErrorRecoveryGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ErrorRecoveryGoal)))
  "Returns full string definition for message of type 'ErrorRecoveryGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ErrorRecoveryGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ErrorRecoveryGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ErrorRecoveryGoal
))
